apiVersion: v1
kind: ConfigMap
metadata:
  name: webapp-config
  namespace: webapp
data:
  app.properties: |
    # Application Configuration
    app.name=Demo WebApp
    app.version=1.0.0
    
    # Server Configuration
    server.port=3000
    server.host=0.0.0.0
    
    # Logging Configuration
    log.level=info
    log.format=json
    
    # Health Check Configuration
    health.check.interval=30000
    
  nginx.conf: |
    upstream webapp {
        server webapp-service:80;
    }
    
    server {
        listen 80;
        server_name localhost;
        
        location / {
            proxy_pass http://webapp;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
        
        location /health {
            access_log off;
            return 200 "healthy\n";
            add_header Content-Type text/plain;
        }
    }
